Rebuilt /w old endpoints
Metatavu/time-bank-api-spec pull request #4
Opened 2022-05-10 12:52 UTC by villejuutila

2022-05-11 09:04 UTC, jarinykanen requested changes

2022-05-11 09:04 UTC, jarinykanen commented on swagger.yaml
> +          $ref: '#/components/schemas/TimeEntryTotalSpan'
What is this id field?

2022-05-12 09:49 UTC, villejuutila commented on swagger.yaml
> +          $ref: '#/components/schemas/TimeEntryTotalSpan'
Done

2022-05-12 09:49 UTC, villejuutila commented on swagger.yaml
>      TimeEntry:
Done

2022-05-12 09:49 UTC, villejuutila commented on swagger.yaml
>          externalId:
Done

2022-05-12 09:49 UTC, villejuutila commented on swagger.yaml
> +            $ref: "#/components/schemas/Timespan"
Done. Should the endpoint be _/v1/persons/_ instead? Otherwise we end up having _/person/_ and _/persons/_ which sounds a bit too complicated.

2022-05-12 09:49 UTC, villejuutila commented on swagger.yaml
> +            type: string
Done

2022-05-12 09:49 UTC, villejuutila commented on swagger.yaml
>          first_name:
Done

2022-05-12 09:49 UTC, villejuutila commented on swagger.yaml
> +          type: string
Done

2022-05-12 09:49 UTC, villejuutila commented on swagger.yaml
> +    PersonData:
Done

2022-05-12 09:49 UTC, villejuutila commented on swagger.yaml
> +        - Timebank
Done

2022-05-12 09:50 UTC, villejuutila commented on swagger.yaml
> +            type: string
Done

2022-05-12 10:18 UTC, villejuutila commented on swagger.yaml
> +            type: string
Done

2022-05-12 10:19 UTC, villejuutila commented on swagger.yaml
> +            type: string
Done

2022-05-12 10:19 UTC, villejuutila commented on swagger.yaml
> +      operationId: getPersons
Done

2022-05-12 10:23 UTC, villejuutila commented on swagger.yaml
> +  /v1/entries/{personId}:
Done

2022-05-12 10:23 UTC, villejuutila commented on swagger.yaml
> +            format: uuid
Done

2022-05-12 10:24 UTC, villejuutila commented on swagger.yaml
> +      operationId: syncTimeFromForecast
Done

2022-05-12 11:24 UTC, jarinykanen commented
Change numbers to to integers where it is possible

2022-10-03 09:25 UTC, closed without merging